import localFont from "next/font/local";
import "./globals.css";
import Footer from "./component/Footer";
import Header from "./component/Header";
import { SearchProvider } from "./component/search";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SearchProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        >
          <Header></Header>
          <main className="container mx-auto flex-grow">{children}</main>
          <Footer></Footer>
        </body>
      </html>
    </SearchProvider>
  );
}
